spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/gplx
    username: gplx
    password: gplx

server:
  port: ${SERVER_PORT:8081}

app:
  cors:
    allowed-origin: http://localhost:5173
